config/routes.rb
Rails.application.routes.draw do
  devise_for :creators
  resources :campaigns
  resources :contacts
  resource  :session

  get '/invite/:id' => 'static#invite'
  get '/link' => 'static#link'
  get '/thankyou' => 'static#thankyou'
  get '/registry' => 'static#registry'
  get '/contacts/new/:campaign_id' => 'contacts#new' , as: 'new_contact_id'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  root to: 'static#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :campaign_contacts
	has_many :contacts, through: :campaign_contacts

	belongs_to :creator
	validates :story, presence: true
	validates :date_of, presence: true
	validates :image, presence: true
end

app/models/campaign_contact.rb
class CampaignContact < ActiveRecord::Base
	belongs_to :campaign
	belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :campaign_contacts
	has_many :campaigns, through: :campaign_contacts

	validates :firstName, presence: true
	validates :lastName, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true

end

app/models/creator.rb
class Creator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :campaigns
  has_many :contacts, through: :campaigns
  
end

app/models/user.rb
class User < ActiveRecord::Base


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	 private
	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end

	  helper_method :current_user
	

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
    @current = current_creator
    @current_id = current_creator.id
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @current = current_creator
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
    @current = current_creator
  end

  # GET /campaigns/1/edit
  def edit
    @current = current_creator
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    respond_to do |format|
      if @campaign.save
        @campaign.update(:creator_id => current_creator.id)
        format.html { redirect_to '/link', notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully erased.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:story, :date_of, :image)
    end
end

app/controllers/concerns/creators_controller.rb
 class CreatorsController < ActionController::Base
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
	  def create
	    user = User.from_omniauth(env["omniauth.auth"])
	    session[:user_id] = user.id
	    redirect_to root_url
	  end

	  def destroy
	    session[:user_id] = nil
	    redirect_to root_url
	  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @current = current_creator
    @contacts = current_creator.contacts
    #@contacts = Contact.joins(:campaignContacts)
    #.where{Campaign.creator_id = current_creator.id}
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @current = current_creator
  end

  # GET /contacts/new
  def new
    @current = current_creator
    @contact = Contact.new
    @CC_ID = params[:campaign_id]
  end

  # GET /contacts/1/edit
  def edit
    @current = current_creator
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        @cc = CampaignContact.create(contact_id: @contact.id, campaign_id: params[:campaign_id])
        @contact.update(:campaign_contacts_id => @cc[:id])
        format.html { redirect_to thankyou_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully erased.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName, :email, :phone, :address, :suite, :city, :state, :zip, :campaign_contacts_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def index
		@current = current_creator
	end

	def link
		@current = current_creator
		@link = Campaign.last
	end

	def invite
		@current = current_creator
		@campaign = Campaign.find(params[:id])
	end
	
	def thankyou
		@current = current_creator
	end

	def registry
		@current = current_creator
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
	def image_preview(f)
		url, style =  f.object.image.present? ?  [f.object.image.url, ''] : ['#','display:none;']
		content_tag(:div, nil) do
			concat image_tag url , {id: 'img_prev', style: style}
			concat ''.html_safe
			concat  f.button 'Remove', {type: 'button', class: 'remove_image', style:'display:none;'}
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/campaigns/_form.html.erb
<%= @current_id %>

<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation" onclick="toggle_visibility('error_explanation');">
      <ul>
          <% @campaign.errors.full_messages.each do |message| %>
            <li class="error"><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <!-- begins block for campaign form -->

   <div ng-controller="PopoverDemoCtrl">
    <br>


      <div popover="Add a message for your invitation here" popover-trigger="mouseenter">
        <%= f.text_field :story , :placeholder => " '' WE NEED YOUR ADDRESS '' " %>
      </div>

        <div popover="Now enter the date of your event" popover-trigger="mouseenter"><%= f.text_field :date_of , :placeholder => "MM / DD / YYYY" %>
      </div>

    <div popover="Click here to choose an image to upload" popover-trigger="mouseenter">
      <div id="slider-container">
          <%= image_tag 'slider-bg.png', :id => 'open-selector'%>
       </div>
       <%= image_preview(f) %>

    <%= f.file_field :image %>

  </div>

    <div class="next"><%= image_submit_tag("next.png") %></div>
    <%= f.hidden_field :image_cache %>   
<% end %>
</html>

app/views/campaigns/edit.html.erb
<div id="wrapper">

<%= render 'form' %>

|
<div class="back">
<%= link_to image_submit_tag("back.png"), campaigns_path %>
</div>

</div>

app/views/campaigns/index.html.erb
<div id="campaign_list_wrapper">
    
        <% @campaigns.each do |campaign| %>
          <div class="buffer">
          <span><%= link_to 'Edit', edit_campaign_path(campaign) %></span>
          <span><%= link_to 'Delete', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </div>
          <span class="title buffer"><%= campaign.story %></span>
        <% end %>
    <br />
<div class="next"><%= link_to image_submit_tag("next.png"), contacts_path(@contact)  %>
</div>

app/views/campaigns/new.html.erb
<div id="wrapper"><br>
		<%= render 'form' %>
</div>

app/views/campaigns/show.html.erb
<div id="wrapper">
	<p id="notice"><%= notice %></p>
	  <%= @campaign.story %>
	  <%= @campaign.date_of %>
	  <%= @campaign.image %>
	  <%= link_to 'Edit', edit_campaign_path(@campaign) %> |
		<div class="back">
			<%= link_to image_submit_tag("back.png"), campaigns_path %>
		</div>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
       
        <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li class="error"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="top">
    <%= f.text_field :firstName, autofocus: true, :placeholder => "FIRST NAME" %>
    <%= f.text_field :lastName, :placeholder => "LAST NAME"%>
    <%= f.text_field :email, :placeholder => "EMAIL" %>
    <%= f.text_field :phone, :placeholder => "PHONE NUMBER" %>
    <%= f.text_field :address, :placeholder => "STREET ADDRESS" %>
    <%= f.text_field :suite, :placeholder => "SUITE" %>
    <%= f.text_field :city, :placeholder => "CITY" %>
    <%= f.text_field :state, :placeholder => "STATE" %>
    <%= f.text_field :zip, :placeholder => "ZIP" %>
    <%= hidden_field_tag :campaign_id, @CC_ID %>
</div> 
<div class="next"><%= image_submit_tag("next.png") %>
<div> 
<% end %>

app/views/contacts/edit.html.erb
<div id="wrapper">
	<div id="title">EDIT THIS CONTACT</div>
	<%= render 'form' %>
	</div>
	
</div>

app/views/contacts/index.html.erb
<div id="contact_wrapper">

<%= link_to image_tag("download.png") %> 
<%= link_to image_tag("printer.png"), :class => 'printer' %>

 <div class= "mute contact"> 
  <table>

    <tbody>
      <% @contacts.each do |contact| %>

          <tr>
            <td>
              <a><span><%= link_to 'Edit', edit_contact_path(contact) %></span></a> <span><a><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %></a></span>
              <br />
              <strong class="title"><span><%= contact.firstName %></span>
                <span><%= contact.lastName %></span></strong> <span><span class="sub_title"><%= contact.email %>
                <br />
                </span class="normal_text"><%= contact.phone %></span> 

                <span class="normal_text"><%= contact.address %>, <%= contact.suite %></span>
                <span class="normal_text"><%= contact.city %> <%= contact.state %> <%= contact.zip %></span>
                <br />
                <br />          
            </td>
          </tr>

      <% end %>
    </tbody>
  </table>
</div> 
  <br>
</div>

app/views/contacts/new.html.erb
<div id="wrapper">

	<%= render 'form' %>

</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

  <strong>Firstname:</strong>
  <%= @contact.firstName %>

  <strong>Lastname:</strong>
  <%= @contact.lastName %>

  <strong>Email:</strong>
  <%= @contact.email %>

  <strong>Phone:</strong>
  <%= @contact.phone %>

  <strong>Address:</strong>
  <%= @contact.address %>

  <strong>Suite:</strong>
  <%= @contact.suite %>

  <strong>City:</strong>
  <%= @contact.city %>

  <strong>State:</strong>
  <%= @contact.state %>

  <strong>Zip:</strong>
  <%= @contact.zip %>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<div class="back"><%= link_to image_submit_tag("back.png"), campaigns_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.js"></script>
  <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.11.0.js"></script>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="favicon64.ico"/>
  <link rel="shortcut icon" href="favicon32.ico"/>
  <link rel="shortcut icon" href="favicon24.ico"/>
  <link rel="shortcut icon" href="favicon16.ico"/>
    
  <title>NYA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
            <header>
              <% if !current_page?(root_path) %>
                  <a><%= link_to "", root_path, :class => 'tag' %></a>
              <% end %>
                <div data-target=".navbar-custom" class="wrapper">
                <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
                   <div class="container">
                   <div class="navbar-header">
                       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                      <i class="fa fa-bars"></i>
                      </button>

                   </div>
                        <div class="collapse navbar-collapse navbar-left navbar-main-collapse right" ng-controller="GetStartedCtrl">
                            <ul class="nav navbar-nav">
                                
                                <li class="hidden">
                                   <a href="#page-top"></a> 
                                </li>
                                <li>
                                  <% if @current %>
                                        <a> <%= link_to "Make an invite!", new_campaign_path %></a>
                                    <% else %>
                                        <a><%= link_to "Make an invite!", new_creator_session_path %></a>
                                    <% end %>
                                </li>
                                <li>
                                  <% if @current %>
                                    <li>
                                        <a> <%= link_to "View my Contacts", contacts_path %></a>
                                    </li>
                                    <% else %>
                                    <script type="text/ng-template" id="myModalContent.html">
                                <div class="modal-header">
                                    <h3 class="modal-title">Learn about us!</h3>
                                </div>
                                <div class="modal-body">
                                <p>Have you ever had a hard time getting all of your contacts for an event in a single, <em>easy to access</em> place?</p>
                                </div>
                                <div class="modal-footer">
                                        <button class="btn-warning" ng-click="cancel()">Close</button>
                                </div>
                            </script>
                                        <li ng-click="open('lg')">
                                        <a><%= link_to "Learn about 'Want Your Info'" , '#' %></a>
                                      </li>
                                    <% end %>
                                </li>
                                <li class="page-scroll">
                                    <a><%= link_to "Contact Us", root_path(:anchor => "contact") %></a>
                                </li>
                                <li id="sign-in">
                                    <% if @current %>
                                        <a><%= link_to "Log out", destroy_creator_session_url, :method => :delete %></a>
                                    <% else %>
                                        <a><%= link_to "Log in", new_creator_session_path %></a>
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                        
                    </div>
                    
                </nav>
              </div>
            </header>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

</body>

</html>